// <auto-generated />
using System;
using MaterialPurchase.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaterialPurchase.Infra.Migrations
{
    [DbContext(typeof(MaterialPurchaseContext))]
    partial class MaterialPurchaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Commom.Domain.BaseEntities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "admin",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("FunctionIdRole", b =>
                {
                    b.Property<Guid>("FunctionsIdsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uuid");

                    b.HasKey("FunctionsIdsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("FunctionIdRole");

                    b.HasData(
                        new
                        {
                            FunctionsIdsId = new Guid("641442a0-db41-415a-862a-32c01c200163"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("0c3054ef-dc4a-428d-9f54-cfb3846b142a"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("b1f86d9c-591a-47d3-885d-0ff4c4c3a307"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("55b7457c-0e2a-4715-b86b-92cbd6a52546"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("4a78cace-0c5a-40d0-9605-3d713b6121aa"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("b41af008-1729-4edb-95a3-f46157d8420e"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("3be84b90-5117-4f58-9392-0a9e7ecd5c0b"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("9097b32e-783c-4309-9c23-f6c08252a489"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("241a5ef5-e5aa-4e36-8d2e-6461dcd56298"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("30fff483-1d53-46bb-b5b2-f3f2f64b935a"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("520cea04-f214-4d40-8d62-d3f5c058e869"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("1a425bc2-246c-4cc5-8041-fec431bea70a"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("1499bfea-9baf-45be-b76c-b5f3a65b28c9"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("45b77ac4-436e-4a46-a457-d8e5c1ce9d47"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("e5b34b70-30f7-458b-a2f0-ef2e6c3bd011"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("2aa5ab7e-a149-4e37-a1ce-a8803ead44db"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("c37b998d-d73e-40bb-987d-afea1616d45b"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        },
                        new
                        {
                            FunctionsIdsId = new Guid("3cb2b2cc-7731-404d-9b64-c19e4f9d4c72"),
                            RolesId = new Guid("ae524c8e-27ef-4f62-8d6a-5df0297fb6c4")
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2bc27280-cf98-4116-ad6c-d7cf5179f41e"),
                            CreatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(948),
                            Name = "TIGRE",
                            UpdatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(948)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Construction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Constructions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cad4da64-e4ab-4b4a-8e83-63fc05fefa64"),
                            CorporateName = "Build LTDA",
                            CreatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(1141),
                            NickName = "Build Ltda",
                            UpdatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(1142)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionId");

                    b.ToTable("ConstructionAuthUserGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6389915-3947-46d1-a636-da6f9ad505aa"),
                            ConstructionId = new Guid("cad4da64-e4ab-4b4a-8e83-63fc05fefa64"),
                            CreatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(1541),
                            Priority = 0,
                            UpdatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(1542)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionUserAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorizationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorizationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("ConstructionUserAuthorizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1b505080-5f17-4b2a-84b1-5f43baba35c4"),
                            AuthorizationStatus = 0,
                            AuthorizationUserGroupId = new Guid("e6389915-3947-46d1-a636-da6f9ad505aa"),
                            Comment = "",
                            CreatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(1558),
                            Permissions = 4,
                            UpdatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(1559),
                            UserId = new Guid("4922766e-d3ba-4d4c-99b0-093d5977d41f")
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.FunctionId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FunctionsIds");

                    b.HasData(
                        new
                        {
                            Id = new Guid("641442a0-db41-415a-862a-32c01c200163"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1001",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0c3054ef-dc4a-428d-9f54-cfb3846b142a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1002",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b1f86d9c-591a-47d3-885d-0ff4c4c3a307"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1003",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55b7457c-0e2a-4715-b86b-92cbd6a52546"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1004",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4a78cace-0c5a-40d0-9605-3d713b6121aa"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1005",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("b41af008-1729-4edb-95a3-f46157d8420e"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1006",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3be84b90-5117-4f58-9392-0a9e7ecd5c0b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1007",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9097b32e-783c-4309-9c23-f6c08252a489"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1008",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("241a5ef5-e5aa-4e36-8d2e-6461dcd56298"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1009",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("30fff483-1d53-46bb-b5b2-f3f2f64b935a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1010",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("520cea04-f214-4d40-8d62-d3f5c058e869"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1011",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1a425bc2-246c-4cc5-8041-fec431bea70a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1012",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1499bfea-9baf-45be-b76c-b5f3a65b28c9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1013",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("45b77ac4-436e-4a46-a457-d8e5c1ce9d47"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1014",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e5b34b70-30f7-458b-a2f0-ef2e6c3bd011"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1015",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2aa5ab7e-a149-4e37-a1ce-a8803ead44db"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1016",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c37b998d-d73e-40bb-987d-afea1616d45b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1017",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3cb2b2cc-7731-404d-9b64-c19e4f9d4c72"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "1018",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ItemMaterialPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(13, 4)
                        .HasColumnType("numeric(13,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("ItemMaterialPurchases");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unity")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c855f3cb-6666-4fe2-bf79-a1d8696ef951"),
                            CreatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(734),
                            Name = "TUBO DE PVC",
                            Unity = "Metro",
                            UpdatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(735)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Site")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8299c0dc-927d-45de-b2c8-71c38faf9384"),
                            Cnpj = "02.624.999/0001-23",
                            CreatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(965),
                            Description = "description",
                            Email = "ponto@email.com",
                            Name = "PONTO DO ENCANADOR",
                            Phone = "Phone",
                            Site = "Site.com",
                            UpdatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(965)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Freight")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("LimitDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseAuthUserGroups");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseDeliveryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialPurchaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasPrecision(13, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialPurchaseId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("PurchaseDeliveryItems");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseUserAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorizationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorizationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("PurchaseUserAuthorizations");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4922766e-d3ba-4d4c-99b0-093d5977d41f"),
                            CreatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(438),
                            Role = "admin",
                            UpdatedAt = new DateTime(2023, 2, 9, 21, 1, 52, 6, DateTimeKind.Local).AddTicks(446),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("FunctionIdRole", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.FunctionId", null)
                        .WithMany()
                        .HasForeignKey("FunctionsIdsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Commom.Domain.BaseEntities.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Construction", b =>
                {
                    b.OwnsOne("MaterialPurchase.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ConstructionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.HasKey("ConstructionId");

                            b1.ToTable("Constructions");

                            b1.WithOwner()
                                .HasForeignKey("ConstructionId");

                            b1.HasData(
                                new
                                {
                                    ConstructionId = new Guid("cad4da64-e4ab-4b4a-8e83-63fc05fefa64"),
                                    City = "Piracicaba",
                                    Country = "Brasil",
                                    State = "Sao Paulo",
                                    Street = "Dom Pedro",
                                    ZipCode = "99999-000"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Construction", "Construction")
                        .WithMany("PurchasingAuthorizationUserGroups")
                        .HasForeignKey("ConstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Construction");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionUserAuthorization", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", "AuthorizationUserGroup")
                        .WithMany("UserAuthorizations")
                        .HasForeignKey("AuthorizationUserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizationUserGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ItemMaterialPurchase", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Materials")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Material");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Provider", b =>
                {
                    b.OwnsOne("MaterialPurchase.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ProviderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.HasKey("ProviderId");

                            b1.ToTable("Providers");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");

                            b1.HasData(
                                new
                                {
                                    ProviderId = new Guid("8299c0dc-927d-45de-b2c8-71c38faf9384"),
                                    City = "Piracicaba",
                                    Country = "Brasil",
                                    State = "Sao Paulo",
                                    Street = "Dom Pedro",
                                    ZipCode = "99999-000"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Construction", "Construction")
                        .WithMany()
                        .HasForeignKey("ConstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Construction");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Purchase", "Purchase")
                        .WithMany("AuthorizationUserGroups")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseDeliveryItem", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.ItemMaterialPurchase", "MaterialPurchase")
                        .WithMany()
                        .HasForeignKey("MaterialPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseDeliveries")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialPurchase");

                    b.Navigation("Purchase");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseUserAuthorization", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", "AuthorizationUserGroup")
                        .WithMany("UserAuthorizations")
                        .HasForeignKey("AuthorizationUserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizationUserGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Construction", b =>
                {
                    b.Navigation("PurchasingAuthorizationUserGroups");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", b =>
                {
                    b.Navigation("UserAuthorizations");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("AuthorizationUserGroups");

                    b.Navigation("Materials");

                    b.Navigation("PurchaseDeliveries");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", b =>
                {
                    b.Navigation("UserAuthorizations");
                });
#pragma warning restore 612, 618
        }
    }
}
