// <auto-generated />
using System;
using MaterialPurchase.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MaterialPurchase.Infra.Migrations
{
    [DbContext(typeof(MaterialPurchaseContext))]
    partial class MaterialPurchaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b11c344b-b3f5-4b49-a33f-89d7e945c339"),
                            CreatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9311),
                            Description = "description",
                            Name = "TIGRE",
                            UpdatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9312)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Construction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Constructions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cad4da64-e4ab-4b4a-8e83-63fc05fefa64"),
                            CorporateName = "Build LTDA",
                            CreatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9698),
                            NickName = "Build Ltda",
                            UpdatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9700)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionId");

                    b.ToTable("ConstructionAuthUserGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6389915-3947-46d1-a636-da6f9ad505aa"),
                            ConstructionId = new Guid("cad4da64-e4ab-4b4a-8e83-63fc05fefa64"),
                            CreatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9915),
                            UpdatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9917)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionUserAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorizationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorizationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("ConstructionUserAuthorizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("404d1ea8-8853-45b7-b9f3-02888579d5a2"),
                            AuthorizationStatus = 0,
                            AuthorizationUserGroupId = new Guid("e6389915-3947-46d1-a636-da6f9ad505aa"),
                            Comment = "",
                            CreatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9952),
                            Permissions = 3,
                            UpdatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9953),
                            UserId = new Guid("4922766e-d3ba-4d4c-99b0-093d5977d41f")
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ItemMaterialPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(13, 4)
                        .HasColumnType("numeric(13,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("ItemMaterialPurchases");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unity")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31f57a85-0dcc-4c0d-ba9c-9e66886c8612"),
                            CreatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9273),
                            Description = "description",
                            Name = "TUBO DE PVC",
                            Unity = "Metro",
                            UpdatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9275)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("character varying(18)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Site")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8299c0dc-927d-45de-b2c8-71c38faf9384"),
                            Cnpj = "02.624.999/0001-23",
                            CreatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9412),
                            Description = "description",
                            Email = "ponto@email.com",
                            Name = "PONTO DO ENCANADOR",
                            Phone = "Phone",
                            Site = "Site.com",
                            UpdatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9414)
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstructionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Freight")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("LimitDeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConstructionId");

                    b.HasIndex("ProviderId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseAuthUserGroups");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseDeliveryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialPurchaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uuid");

                    b.Property<double>("Quantity")
                        .HasPrecision(13, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialPurchaseId");

                    b.HasIndex("PurchaseId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("PurchaseDeliveryItems");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseUserAuthorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AuthorizationStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("AuthorizationUserGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Permissions")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationUserGroupId");

                    b.HasIndex("UserId");

                    b.ToTable("PurchaseUserAuthorizations");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4922766e-d3ba-4d4c-99b0-093d5977d41f"),
                            CreatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9010),
                            Role = "11",
                            UpdatedAt = new DateTime(2023, 1, 25, 23, 27, 37, 222, DateTimeKind.Local).AddTicks(9021),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Construction", b =>
                {
                    b.OwnsOne("MaterialPurchase.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ConstructionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.HasKey("ConstructionId");

                            b1.ToTable("Constructions");

                            b1.WithOwner()
                                .HasForeignKey("ConstructionId");

                            b1.HasData(
                                new
                                {
                                    ConstructionId = new Guid("cad4da64-e4ab-4b4a-8e83-63fc05fefa64"),
                                    City = "Piracicaba",
                                    Country = "Brasil",
                                    State = "Sao Paulo",
                                    Street = "Dom Pedro",
                                    ZipCode = "99999-000"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Construction", "Construction")
                        .WithMany("PurchasingAuthorizationUserGroups")
                        .HasForeignKey("ConstructionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Construction");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionUserAuthorization", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", "AuthorizationUserGroup")
                        .WithMany("UserAuthorizations")
                        .HasForeignKey("AuthorizationUserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizationUserGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ItemMaterialPurchase", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Materials")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Material");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Provider", b =>
                {
                    b.OwnsOne("MaterialPurchase.Domain.Entities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ProviderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)");

                            b1.HasKey("ProviderId");

                            b1.ToTable("Providers");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");

                            b1.HasData(
                                new
                                {
                                    ProviderId = new Guid("8299c0dc-927d-45de-b2c8-71c38faf9384"),
                                    City = "Piracicaba",
                                    Country = "Brasil",
                                    State = "Sao Paulo",
                                    Street = "Dom Pedro",
                                    ZipCode = "99999-000"
                                });
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Construction", "Construction")
                        .WithMany()
                        .HasForeignKey("ConstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Construction");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.Purchase", "Purchase")
                        .WithMany("AuthorizationUserGroups")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseDeliveryItem", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.ItemMaterialPurchase", "MaterialPurchase")
                        .WithMany()
                        .HasForeignKey("MaterialPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.Purchase", "Purchase")
                        .WithMany("PurchaseDeliveries")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaterialPurchase");

                    b.Navigation("Purchase");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseUserAuthorization", b =>
                {
                    b.HasOne("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", "AuthorizationUserGroup")
                        .WithMany("UserAuthorizations")
                        .HasForeignKey("AuthorizationUserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaterialPurchase.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorizationUserGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Construction", b =>
                {
                    b.Navigation("PurchasingAuthorizationUserGroups");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.ConstructionAuthUserGroup", b =>
                {
                    b.Navigation("UserAuthorizations");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("AuthorizationUserGroups");

                    b.Navigation("Materials");

                    b.Navigation("PurchaseDeliveries");
                });

            modelBuilder.Entity("MaterialPurchase.Domain.Entities.PurchaseAuthUserGroup", b =>
                {
                    b.Navigation("UserAuthorizations");
                });
#pragma warning restore 612, 618
        }
    }
}
