// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantManagement.Infra.Persistence;

#nullable disable

namespace TenantManagement.Infra.Migrations
{
    [DbContext(typeof(TenantManagementDbContext))]
    [Migration("20260813165708_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tenant_management")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenantManagement.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PrimaryTaxId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("primary_tax_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuspensionReason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("suspension_reason");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trade_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryTaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_primary_tax_id");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_tenants_created_at_id");

                    b.ToTable("tenants", "tenant_management");
                });

            modelBuilder.Entity("TenantManagement.Infra.Persistence.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.ToTable("client_requests", "tenant_management");
                });

            modelBuilder.Entity("TenantManagement.Domain.Tenants.Tenant", b =>
                {
                    b.OwnsOne("TenantManagement.Domain.SharedKernel.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_city");

                            b1.Property<string>("Complement")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_complement");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_country");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("address_neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("address_number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("address_state");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants", "tenant_management");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("TenantManagement.Domain.SharedKernel.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants", "tenant_management");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsMany("TenantManagement.Domain.Tenants.TenantMembership", "Memberships", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("email");

                            b1.Property<Guid?>("IdentityUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("identity_user_id");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<int>("Provisioning")
                                .HasColumnType("integer")
                                .HasColumnName("provisioning");

                            b1.Property<DateTime?>("RevokedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("revoked_at");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId", "Email")
                                .IsUnique()
                                .HasDatabaseName("ix_tenant_memberships_tenant_email");

                            b1.ToTable("tenant_memberships", "tenant_management");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsMany("TenantManagement.Domain.Tenants.TenantProduct", "Products", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("ActivatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("activated_at");

                            b1.Property<int>("Code")
                                .HasColumnType("integer")
                                .HasColumnName("product_code");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime?>("DeactivatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("deactivated_at");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("is_active");

                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid")
                                .HasColumnName("tenant_id");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("Id");

                            b1.HasIndex("TenantId", "Code")
                                .IsUnique()
                                .HasDatabaseName("ix_tenant_products_tenant_code");

                            b1.ToTable("tenant_products", "tenant_management");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("Memberships");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
