version: '3.4'

services:
  peoplemanagement.api:
    profiles: ["api"]
    image: ${DOCKER_REGISTRY-}peoplemanagementapi
    build:
      context: .
      dockerfile: Services/PeopleManagement/PeopleManagement.API/Dockerfile
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "443"
        ASPNETCORE_ENVIRONMENT: Developmen
        PUPPETEER_EXECUTABLE_PATH: "/usr/bin/google-chrome-unstable"
    volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    ports:
        - 8040:80
        - 8041:443
    depends_on:
        - peoplemanagement.db
        - blob-azure-storage
        - keycloak

  peoplemanagement.db:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - peoplemanagement-db:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "5up3rS3nh@"
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - 8042:5432

  blob-azure-storage:
    image: mcr.microsoft.com/azure-storage/azurite:3.34.0
    container_name: blob-azure-storage
    volumes:
        - ./.containers/blob_storage/data:/data
    ports:
        - 10000:10000
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.4
    command: start-dev
    environment:
      KC_HOSTNAME: http://192.168.15.11:8080
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: Admin
      KEYCLOAK_ADMIN_PASSWORD: Admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak.db/keycloakDb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: 5up3rS3nh@
      KC_FEATURES: hostname:v2
    ports:
      - 8082:8082
      - 8080:8080
    depends_on:
      - keycloak.db
                    
  keycloak.db:
    image: postgres:16.4-alpine
    restart: always
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloakDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 5up3rS3nh@
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
        - 8081:5432

volumes:
  peoplemanagement-db:
  keycloak-db:
  
