version: '3.4'

services:
  peoplemanagement.api:
    image: ${DOCKER_REGISTRY-}peoplemanagementapi
    build:
      context: .
      dockerfile: Services/PeopleManagement/PeopleManagement.API/Dockerfile
    environment:
        ASPNETCORE_URLS: "https://+;http://+"
        ASPNETCORE_HTTPS_PORT: "443"
        ASPNETCORE_ENVIRONMENT: Development
    volumes:
        - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    ports:
        - 8040:80
        - 8041:443
    depends_on:
        - peoplemanagement.db

  peoplemanagement.db:
    image: postgres:15.1-alpine
    restart: always
    environment:
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "5up3rS3nh@"
    ports:
        - 8042:5432


