// <auto-generated />
using System;
using BillPayment.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BillPayment.Infra.Migrations
{
    [DbContext(typeof(BillPaymentDbContext))]
    [Migration("20260827202405_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bill_payment")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BillPayment.Domain.Bills.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("dedup_key");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Instruments")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("instruments");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Lookup")
                        .HasColumnType("jsonb")
                        .HasColumnName("lookup");

                    b.Property<string>("LookupHistory")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lookup_history");

                    b.Property<Guid?>("PayeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_id");

                    b.Property<string>("PixLookup")
                        .HasColumnType("jsonb")
                        .HasColumnName("pix_lookup");

                    b.Property<int>("Rail")
                        .HasColumnType("integer")
                        .HasColumnName("rail");

                    b.Property<string>("Reading")
                        .HasColumnType("jsonb")
                        .HasColumnName("reading");

                    b.Property<int?>("Risk")
                        .HasColumnType("integer")
                        .HasColumnName("risk_level");

                    b.Property<int?>("Routing")
                        .HasColumnType("integer")
                        .HasColumnName("routing_confidence");

                    b.Property<DateOnly?>("ScheduledFor")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_for");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_bills_dedup_key_active")
                        .HasFilter("\"dedup_key\" IS NOT NULL AND \"status\" NOT IN (5, 9)");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("ix_bills_tenant_created");

                    b.HasIndex("TenantId", "DueDate")
                        .HasDatabaseName("ix_bills_tenant_due_date");

                    b.ToTable("bills", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.CaptureItems.CaptureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("artifact_key");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uuid")
                        .HasColumnName("bill_id");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DiscardedOf")
                        .HasColumnType("uuid")
                        .HasColumnName("discarded_of");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dismissed_at");

                    b.Property<Guid?>("DismissedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("dismissed_by");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_message_id");

                    b.Property<int?>("Extraction")
                        .HasColumnType("integer")
                        .HasColumnName("extraction_method");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("internet_message_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<bool>("ManuallySupplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("manually_supplied");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int?>("Routing")
                        .HasColumnType("integer")
                        .HasColumnName("routing_confidence");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("sender");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_url");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_key");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnlockedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("unlocked_by");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ContentHash")
                        .HasDatabaseName("ix_capture_items_tenant_content_hash");

                    b.HasIndex("Status", "ReceivedAt", "Id")
                        .HasDatabaseName("ix_capture_items_worker_queue");

                    b.HasIndex("TenantId", "Status", "ReceivedAt")
                        .HasDatabaseName("ix_capture_items_tenant_status_received");

                    b.HasIndex("TenantId", "SourceId", "ExternalMessageId", "ArtifactKey")
                        .IsUnique()
                        .HasDatabaseName("ix_capture_items_tenant_source_message_artifact");

                    b.ToTable("capture_items", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.CaptureSources.CaptureSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateOnly?>("CaptureSince")
                        .HasColumnType("date")
                        .HasColumnName("capture_since");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Credential")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("credential_ref");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_sync_error");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .HasDatabaseName("ix_capture_sources_address_global");

                    b.HasIndex("IsEnabled", "LastSyncAt")
                        .HasDatabaseName("ix_capture_sources_enabled_last_sync");

                    b.HasIndex("TenantId", "Address")
                        .IsUnique()
                        .HasDatabaseName("ix_capture_sources_tenant_address");

                    b.ToTable("capture_sources", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.CapturedMessages.CapturedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BodyContentType")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("body_content_type");

                    b.Property<string>("BodyStorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("body_storage_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("external_message_id");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("InternetMessageId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("internet_message_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("sender");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "ReceivedAt", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_captured_messages_tenant_received");

                    b.HasIndex("TenantId", "SourceId", "ExternalMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_captured_messages_tenant_source_message");

                    b.ToTable("captured_messages", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.Expectations.BillExpectation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("account_reference");

                    b.Property<int>("AlertLeadDays")
                        .HasColumnType("integer")
                        .HasColumnName("alert_lead_days");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeactivationReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deactivation_reason");

                    b.Property<int>("ExpectedDueDay")
                        .HasColumnType("integer")
                        .HasColumnName("expected_due_day");

                    b.Property<Guid?>("HintSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("hint_source_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer")
                        .HasColumnName("observation_count");

                    b.Property<int>("ObservedLeadDays")
                        .HasColumnType("integer")
                        .HasColumnName("observed_lead_days");

                    b.Property<int>("Origin")
                        .HasColumnType("integer")
                        .HasColumnName("origin");

                    b.Property<DateOnly?>("PausedUntil")
                        .HasColumnType("date")
                        .HasColumnName("paused_until");

                    b.Property<Guid>("PayeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("payee_id");

                    b.Property<int>("Recurrence")
                        .HasColumnType("integer")
                        .HasColumnName("recurrence");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "UpdatedAt")
                        .HasDatabaseName("ix_bill_expectations_active_updated");

                    b.HasIndex("TenantId", "PayeeId", "AccountReference")
                        .IsUnique()
                        .HasDatabaseName("ix_bill_expectations_tenant_payee_account");

                    b.ToTable("bill_expectations", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.Payees.Payee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AcceptedBanks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("accepted_banks");

                    b.Property<string>("Aliases")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("aliases");

                    b.Property<string>("AmountPolicy")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("amount_policy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .HasDatabaseName("ix_payees_tax_id_global");

                    b.HasIndex("TenantId", "TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_payees_tenant_tax_id");

                    b.ToTable("payees", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.PayerProfiles.PayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalTaxIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_tax_ids");

                    b.Property<string>("AsaasAccountRef")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("asaas_account_ref");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("legal_name");

                    b.Property<bool>("MatchByCnpjRoot")
                        .HasColumnType("boolean")
                        .HasColumnName("match_by_cnpj_root");

                    b.Property<string>("PrimaryTaxId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("primary_tax_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_payer_profiles_tenant");

                    b.ToTable("payer_profiles", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.Retention.CaptureRetentionPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Window")
                        .HasColumnType("integer")
                        .HasColumnName("window_days");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_capture_retention_policies_tenant");

                    b.ToTable("capture_retention_policies", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.TrustedOrigins.TrustedOrigin", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<int>("Decision")
                        .HasColumnType("integer")
                        .HasColumnName("decision");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Value")
                        .HasDatabaseName("ix_trusted_origins_tenant_value");

                    b.HasIndex("TenantId", "Kind", "Value")
                        .IsUnique()
                        .HasDatabaseName("ix_trusted_origins_tenant_kind_value");

                    b.ToTable("trusted_origins", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Infra.Persistence.ClientRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.ToTable("client_requests", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Infra.Persistence.OutboxDeadLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("Id");

                    b.ToTable("outbox_dead_letters", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Infra.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_unprocessed")
                        .HasFilter("processed = false");

                    b.ToTable("outbox_messages", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Infra.Persistence.ProcessedEventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.HasKey("Id");

                    b.ToTable("processed_event_log", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Infra.Persistence.TenantSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("DekNonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("dek_nonce");

                    b.Property<byte[]>("DekTag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("dek_tag");

                    b.Property<int>("KekVersion")
                        .HasColumnType("integer")
                        .HasColumnName("kek_version");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("tag");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("wrapped_dek");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Kind")
                        .HasDatabaseName("ix_tenant_secrets_tenant_kind");

                    b.ToTable("tenant_secrets", "bill_payment");
                });

            modelBuilder.Entity("BillPayment.Domain.Bills.Bill", b =>
                {
                    b.OwnsOne("BillPayment.Domain.Bills.ApprovalRecord", "Approval", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("DecidedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("approval_decided_at");

                            b1.Property<Guid>("DecidedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("approval_decided_by");

                            b1.Property<int>("Decision")
                                .HasColumnType("integer")
                                .HasColumnName("approval_decision");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("approval_note");

                            b1.Property<int?>("RiskAtDecision")
                                .HasColumnType("integer")
                                .HasColumnName("approval_risk_at_decision");

                            b1.HasKey("BillId");

                            b1.ToTable("bills", "bill_payment");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("BillPayment.Domain.Bills.BillOrigin", "Origin", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ContentHash")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("origin_content_hash");

                            b1.Property<string>("ExternalMessageId")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("origin_external_message_id");

                            b1.Property<DateTime>("ReceivedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("origin_received_at");

                            b1.Property<string>("SenderAddress")
                                .HasMaxLength(320)
                                .HasColumnType("character varying(320)")
                                .HasColumnName("origin_sender_address");

                            b1.Property<Guid?>("SourceId")
                                .HasColumnType("uuid")
                                .HasColumnName("origin_source_id");

                            b1.Property<int>("SourceKind")
                                .HasColumnType("integer")
                                .HasColumnName("origin_source_kind");

                            b1.Property<string>("StorageKey")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("origin_storage_key");

                            b1.HasKey("BillId");

                            b1.HasIndex("SenderAddress")
                                .HasDatabaseName("ix_bills_origin_sender");

                            b1.ToTable("bills", "bill_payment");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsOne("BillPayment.Domain.Bills.PartyInfo", "ExtractedPayer", b1 =>
                        {
                            b1.Property<Guid>("BillId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("extracted_payer_name");

                            b1.Property<string>("TaxId")
                                .HasMaxLength(14)
                                .HasColumnType("character varying(14)")
                                .HasColumnName("extracted_payer_tax_id");

                            b1.HasKey("BillId");

                            b1.ToTable("bills", "bill_payment");

                            b1.WithOwner()
                                .HasForeignKey("BillId");
                        });

                    b.OwnsMany("BillPayment.Domain.Bills.Checks.BillCheck", "Checks", b1 =>
                        {
                            b1.Property<Guid>("bill_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.Property<DateTime>("EvaluatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("evaluated_at");

                            b1.Property<string>("Evidence")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("evidence");

                            b1.Property<int>("Outcome")
                                .HasColumnType("integer")
                                .HasColumnName("outcome");

                            b1.Property<string>("ReasonCode")
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("reason_code");

                            b1.Property<int>("Severity")
                                .HasColumnType("integer")
                                .HasColumnName("severity");

                            b1.HasKey("bill_id", "Type");

                            b1.ToTable("bill_checks", "bill_payment");

                            b1.WithOwner()
                                .HasForeignKey("bill_id");
                        });

                    b.Navigation("Approval");

                    b.Navigation("Checks");

                    b.Navigation("ExtractedPayer");

                    b.Navigation("Origin")
                        .IsRequired();
                });

            modelBuilder.Entity("BillPayment.Domain.CaptureSources.CaptureSource", b =>
                {
                    b.OwnsMany("BillPayment.Domain.CaptureSources.MonitoredFolder", "Folders", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime?>("LastSyncAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_sync_at");

                            b1.Property<string>("LastSyncError")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("last_sync_error");

                            b1.Property<string>("Path")
                                .HasMaxLength(250)
                                .HasColumnType("character varying(250)")
                                .HasColumnName("path");

                            b1.Property<string>("SyncCursor")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("sync_cursor");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("capture_source_id")
                                .HasColumnType("uuid")
                                .HasColumnName("capture_source_id");

                            b1.HasKey("Id");

                            b1.HasIndex("capture_source_id", "Path")
                                .IsUnique()
                                .HasDatabaseName("ix_capture_source_folders_source_path");

                            NpgsqlIndexBuilderExtensions.AreNullsDistinct(b1.HasIndex("capture_source_id", "Path"), false);

                            b1.ToTable("capture_source_folders", "bill_payment");

                            b1.WithOwner()
                                .HasForeignKey("capture_source_id");
                        });

                    b.Navigation("Folders");
                });

            modelBuilder.Entity("BillPayment.Domain.CapturedMessages.CapturedMessage", b =>
                {
                    b.OwnsMany("BillPayment.Domain.CapturedMessages.MessageArtifact", "Artifacts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ArtifactKey")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("artifact_key");

                            b1.Property<Guid?>("BillId")
                                .HasColumnType("uuid")
                                .HasColumnName("bill_id");

                            b1.Property<Guid?>("CaptureItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("capture_item_id");

                            b1.Property<string>("ContentType")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("content_type");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateTime?>("DecidedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("decided_at");

                            b1.Property<string>("FileName")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("file_name");

                            b1.Property<int>("Outcome")
                                .HasColumnType("integer")
                                .HasColumnName("outcome");

                            b1.Property<string>("Reason")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("reason");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<Guid>("captured_message_id")
                                .HasColumnType("uuid")
                                .HasColumnName("captured_message_id");

                            b1.HasKey("Id");

                            b1.HasIndex("captured_message_id", "ArtifactKey")
                                .IsUnique()
                                .HasDatabaseName("ix_captured_message_artifacts_message_key");

                            b1.ToTable("captured_message_artifacts", "bill_payment");

                            b1.WithOwner()
                                .HasForeignKey("captured_message_id");
                        });

                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("BillPayment.Domain.Expectations.BillExpectation", b =>
                {
                    b.OwnsMany("BillPayment.Domain.Expectations.ExpectationCycle", "Cycles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateOnly>("AlertAt")
                                .HasColumnType("date")
                                .HasColumnName("alert_at");

                            b1.Property<string>("Alerts")
                                .IsRequired()
                                .HasColumnType("jsonb")
                                .HasColumnName("alerts");

                            b1.Property<Guid?>("BlockedByCaptureItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("blocked_by_capture_item_id");

                            b1.Property<int>("Competence")
                                .HasColumnType("integer")
                                .HasColumnName("competence");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<DateOnly>("ExpectedDueDate")
                                .HasColumnType("date")
                                .HasColumnName("expected_due_date");

                            b1.Property<Guid?>("FulfilledByBillId")
                                .HasColumnType("uuid")
                                .HasColumnName("fulfilled_by_bill_id");

                            b1.Property<int?>("MissReason")
                                .HasColumnType("integer")
                                .HasColumnName("miss_reason");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.Property<string>("WaiveReason")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("waive_reason");

                            b1.Property<Guid?>("WaivedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("waived_by");

                            b1.Property<Guid>("bill_expectation_id")
                                .HasColumnType("uuid")
                                .HasColumnName("bill_expectation_id");

                            b1.HasKey("Id");

                            b1.HasIndex("bill_expectation_id", "Competence")
                                .IsUnique()
                                .HasDatabaseName("ix_bill_expectation_cycles_expectation_competence");

                            b1.ToTable("bill_expectation_cycles", "bill_payment");

                            b1.WithOwner()
                                .HasForeignKey("bill_expectation_id");
                        });

                    b.Navigation("Cycles");
                });
#pragma warning restore 612, 618
        }
    }
}
