global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using MediatR;
global using PeopleManagement.Application.Commands.DTO;
global using Microsoft.Extensions.Logging;
global using PeopleManagement.Domain.AggregatesModel.CompanyAggregate;