name: Publish People Management API

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'server/Services/PeopleManagement/**'
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Magalu Cloud Container Registry
        uses: docker/login-action@v2
        with:
          # O endereço do seu Container Registry da Magalu Cloud
          registry: container-registry.br-se1.magalu.cloud
          # Use os segredos do GitHub para suas credenciais do Magalu Cloud CR
          username: ${{ secrets.MAGALU_CR_USERNAME }}
          password: ${{ secrets.MAGALU_CR_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./server/Services/PeopleManagement/.
          file: ./server/Services/PeopleManagement/PeopleManagement.API/Dockerfile
          push: true
          # As tags devem incluir o endereço completo do registro
          # Substitua 'seu-repositorio' pelo nome do seu repositório no Magalu Cloud CR, se aplicável
          tags: container-registry.br-se1.magalu.cloud/rufino-project/people-management-api:latest

